spring.application.name=mailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ssatishjadhav1@gmail.com
spring.mail.password=iujxpykkmcnlknwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8080
server.address=0.0.0.0